const episodeRegistry = [
  {
    id: "episode_01_second_cutting_introduction",
    episode_number: 1,
    title: "Where the Story Begins: Land, Lineage, Meaning",
    guest: "Dr Shannon Gonsoulin",
    themes: ["pasture biology", "land stewardship", "food systems"],
    date: "2026",
    description: "A documentary podcast exploring the systems that connect land, animals, food, and people.",
    connections: ["second_cutting", "glc", "media", "data"],
    listen_url: "https://podcasts.apple.com/us/podcast/second-cutting/id1865905475?i=1000743510333",
    spotify_url: "https://creators.spotify.com/pod/profile/second-cutting/episodes/Where-the-Story-Begins-Land--Lineage--Meaning-e3d35u0",
    watch_url: "",
    transcript_url: ""
  },
  {
    id: "episode_02_living_landscape",
    episode_number: 2,
    title: "Reading the Season",
    guest: "Dr Shannon Gonsoulin",
    themes: ["grass fed beef", "ecology", "working landscapes"],
    date: "2026",
    description: "A conversation about how working ranches hold memory in soil, grass, animals, and the people who care for them.",
    connections: ["second_cutting", "glc", "data"],
    listen_url: "https://podcasts.apple.com/us/podcast/second-cutting/id1865905475?i=1000745624724",
    spotify_url: "https://open.spotify.com/episode/3NTSKcRPGYp5vp3dIoJVd0?si=o_xxJt0hSJ6U-_e1981Mjg",
    watch_url: "",
    transcript_url: ""
  },
  {
    id: "episode_03_land_remembers",
    episode_number: 3,
    title: "The Land Remembers",
    guest: "Dr Shannon Gonsoulin",
    themes: ["land memory", "ecology", "stewardship"],
    date: "2026",
    description: "A conversation about how landscapes retain memory through ecology, practice, and time.",
    connections: ["second_cutting", "glc", "data"],
    listen_url: "https://podcasts.apple.com/us/podcast/second-cutting/id1865905475?i=1000747581249",
    spotify_url: "https://creators.spotify.com/pod/profile/second-cutting/episodes/The-Land-Remembers-e3eg0vk",
    watch_url: "",
    transcript_url: ""
  },
  {
    id: "episode_04_lines_on_the_land",
    episode_number: 4,
    title: "Lines on the Land",
    guest: "Dr Shannon Gonsoulin",
    themes: ["mapping", "land use", "working landscapes"],
    date: "2026",
    description: "A conversation about boundaries, use, and the visible and invisible lines that shape the land.",
    connections: ["second_cutting", "glc", "media"],
    listen_url: "https://podcasts.apple.com/us/podcast/second-cutting/id1865905475?i=1000749982167",
    spotify_url: "https://creators.spotify.com/pod/profile/second-cutting/episodes/Lines-on-the-Land-e3f5skd",
    watch_url: "",
    transcript_url: ""
  },
  {
    id: "episode_05_time_changes_the_math",
    episode_number: 5,
    title: "Time Changes the Math",
    guest: "Dr Shannon Gonsoulin",
    themes: ["time", "economics", "agriculture"],
    date: "2026",
    description: "A conversation about how time changes the economics, biology, and expectations of agricultural systems.",
    connections: ["second_cutting", "glc", "data"],
    listen_url: "https://podcasts.apple.com/us/podcast/second-cutting/id1865905475?i=1000752307523",
    spotify_url: "https://creators.spotify.com/pod/profile/second-cutting/episodes/Time-Changes-the-Math-e3fp4no",
    watch_url: "",
    transcript_url: ""
  },
  {
    id: "episode_06_meadow_pharmacy",
    episode_number: 6,
    title: "The Meadow Is the Pharmacy, Part 1",
    guest: "Dr Shannon Gonsoulin",
    themes: ["soil biology", "grass fed beef", "human health"],
    date: "2026",
    description: "A conversation about how soil, grass, cattle, and people form a biological chain.",
    connections: ["second_cutting", "glc", "media"],
    listen_url: "https://podcasts.apple.com/us/podcast/second-cutting/id1865905475?i=1000755405420",
    spotify_url: "https://creators.spotify.com/pod/profile/second-cutting/episodes/The-Meadow-is-the-Pharmacy--part-1-e3gfiti",
    watch_url: "",
    transcript_url: ""
  }
];
